name: Create Repository

on:
    workflow_dispatch:
        inputs: 
            name-repo:
                description: "Repository's name"
                required: true

jobs:
    create-repo:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository content
              uses: actions/checkout@v3 

            - name: TESTE
              run: echo ${{ github.event.inputs.name-repo }}

            - name: Creating repository
              env:
                GH_TOKEN: ${{ secrets.TEST_TOKEN_SECRET }}
              run: |
                curl -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: token ${{ secrets.ORG_ADMIN_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                -H "User-Agent: GitHubActions" \
                --data '{"name":"${{ github.event.inputs.name-repo }}"}' \
                https://api.github.com/user/repos

                
            - name: Create readme
              env:
                GH_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
              run: |
                git config --local user.email ${{ secrets.EMAIL }}
                git config --local user.name ${{ secrets.USER_NAME }}
                git clone https://github.com/your-JuliazzeDantas/${{ github.event.inputs.name-repo }}
                cd ${{ github.event.inputs.name-repo }}
                echo "# ${{ github.event.inputs.name-repo }}" > README.md
                git add README.md
                git commit -m "Adicionar README"
                git push
              


