name: Create Repository

on:
    workflow_dispatch:
        inputs: 
            name-repo:
              description: "Repository name"
              required: true
            owner:
              description: "Repository owner"
              required: false
            project:
              description: "Project name"
              required: false
            area:
                description: "Area name"
                required: false

jobs:
    create-repo:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository content
              uses: actions/checkout@v3 

            - name: Setup python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x' 

            - name: Creating repository
              env:
                GH_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
              run: |
                curl -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: token ${{ secrets.ORG_ADMIN_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                -H "User-Agent: GitHubActions" \
                --data '{"name":"${{ github.event.inputs.name-repo }}"}' \
                https://api.github.com/user/repos

            - name: Get Readme Content
              run: |
                export readme_content=$(python3 retorna_conteudo_readme.py '${{ github.event.inputs.name-repo}}' '${{ github.event.inputs.owner}}' '${{ github.event.inputs.project}}' '${{ github.event.inputs.area}}' )
                echo "README_CONTENT=$readme_content" >> $GITHUB_ENV

            - name: Create readme
              env:
                GH_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
              run: |
                curl -L \
                -X PUT \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.ORG_ADMIN_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/JuliazzeDantas/${{ github.event.inputs.name-repo }}/contents/Readme.md \
                -d '{"message":"Repositório do projeto ${{ github.event.inputs.name-repo }} Criado com Sucesso","committer":{"name":"GitHub Actions","email":"githubactions@github.com"},"content":"'"${README_CONTENT}"'""}'
              
                
            - name: Rename default branch
              env:
                GH_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
              run: |
                curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.ORG_ADMIN_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/JuliazzeDantas/${{ github.event.inputs.name-repo }}/branches/master/rename \
                -d '{"new_name":"main"}'

            - name: Get Pull Request Template Content
              run: |
                export pull_request_template_content=$(python3 retorna_conteudo_readme.py '${{ github.event.inputs.name-repo}}' '${{ github.event.inputs.owner}}' '${{ github.event.inputs.project}}' '${{ github.event.inputs.area}}' )
                echo "PULL_REQUEST_TEMPLATE_CONTENT=$pull_request_template_content" >> $GITHUB_ENV
            
            - name: Create pull request template
              env:
                GH_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
              run: |
                curl -L \
                -X PUT \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.ORG_ADMIN_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/JuliazzeDantas/${{ github.event.inputs.name-repo }}/contents/.github/ISSUE_TEMPLATE/template.md \
                -d '{"message":"Repositório do projeto ${{ github.event.inputs.name-repo }} Criado com Sucesso","committer":{"name":"GitHub Actions","email":"githubactions@github.com"},"content":"'"${PULL_REQUEST_TEMPLATE_CONTENT}"'""}'
                







