name: Create Repository

on:
    workflow_dispatch:
        inputs: 
            name-repo:
              description: "Repository name"
              required: true
            owner:
              description: "Repository owner"
              required: false
            project:
              description: "Project name"
              required: false
            area:
                description: "Area name"
                required: false

jobs:
    create-repo:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository content
              uses: actions/checkout@v3 

            - name: Setup python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10' 

            - name: Creating repository
              env:
                GH_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
              run: |
                curl -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: token ${{ secrets.ORG_ADMIN_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                -H "User-Agent: GitHubActions" \
                --data '{"name":"${{ github.event.inputs.name-repo }}"}' \
                https://api.github.com/user/repos

            - name: Get Readme Content
              run: |
                README_CONTENT=$(python3 retorna_conteudo_readme.py ${{ github.event.inputs.name-repo}} ${{ github.event.inputs.owner}} ${{ github.event.inputs.project}} ${{ github.event.inputs.area}} )
            
            - name: Get Readme Content
              run: echo $README_CONTENT

            - name: Create readme
              env:
                GH_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
              run: |
                curl -L \
                -X PUT \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.ORG_ADMIN_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/JuliazzeDantas/${{ github.event.inputs.name-repo }}/contents/Readme.md \
                -d '{"message":"Repositório do projeto ${{ github.event.inputs.name-repo }} Criado com Sucesso","committer":{"name":"GitHub Actions","email":"githubactions@github.com"},"content":"$README_CONTENT"}'
              
                
            - name: Rename default branch
              env:
                GH_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
              run: |
                curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.ORG_ADMIN_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/JuliazzeDantas/${{ github.event.inputs.name-repo }}/branches/master/rename \
                -d '{"new_name":"main"}'








