name: Create Repository

on:
    workflow_dispatch:
        inputs: 
            name-repo:
                description: "Repository's name"
                required: true

jobs:
    create-repo:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository content
              uses: actions/checkout@v3 

            - name: TESTE
              run: echo ${{ github.event.inputs.name-repo }}

            - name: Creating repository
              env:
                GH_TOKEN: ${{ secrets.TEST_TOKEN_SECRET }}
              run: |
                curl -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: token ${{ secrets.ORG_ADMIN_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                -H "User-Agent: GitHubActions" \
                --data '{"name":"${{ github.event.inputs.name-repo }}"}' \
                https://api.github.com/user/repos
            
            - name: Rename default branch
              env:
                GH_TOKEN: ${{ secrets.TEST_TOKEN_SECRET }}
              run: |
                curl -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: token ${{ secrets.ORG_ADMIN_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                -H "User-Agent: GitHubActions" \
                -d '{"new_name":"main"}' \
                https://api.github.com/repos/JuliazzeDantas/${{ github.event.inputs.name-repo }}/branches/master/rename