name: Create Repository

on:
    workflow_dispatch:
        inputs: 
            name-repo:
                description: "Repository's name"
                required: true

jobs:
    create-repo:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository content
              uses: actions/checkout@v3 

            - name: TESTE
              run: echo ${{ github.event.inputs.name-repo }}

            - name: Creating repository
              env:
                GH_TOKEN: ${{ secrets.TEST_TOKEN_SECRET }}
              run: |
                curl -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: token ${{ secrets.ORG_ADMIN_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                -H "User-Agent: GitHubActions" \
                --data '{"name":"${{ github.event.inputs.name-repo }}"}' \
                https://api.github.com/user/repos

            - name: Create readme
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                echo "# Repositorio-automatico" >> README.md
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git init
                git add README.md
                git commit -m "first commit"
                git branch -M main
                git remote add origin git@github.com:JuliazzeDantas/Repositorio-automatico.git
                git push -u origin main
                
            