name: Create Jwt

on:
    workflow_dispatch:
        inputs:
            key:
                description: 'Issue Key'
                required: true
            specifications:
                description: 'Private Key'
                required: true

jobs:
    create-jwt:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v4
            - 
                name: Setup python
                uses: actions/setup-python@v5
                with:
                    python-version: '3.10' 
            - 
                name: Install python packages
                run: |
                  python -m pip install --upgrade pip
                  pip install -r create_jwt/requirements.txt
            -
              name: Generate GitHub App Token
              id: generate-token
              uses: actions/create-github-app-token@v1
              with:
                app-id: ${{ secrets.APP_ID }}
                private-key: ${{ secrets.PRIVATE_KEY }}
                owner: JuliazzeDantas
                repositories: |
                  Test-GitHub-Actions
            -
                name: Start Jira Trigger
                run: |
                    curl -L \
                    -X POST \
                    -H "Accept: application/vnd.github+json" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    -H "Accept: application/vnd.github.v3+json" \
                    -H "Content-Type: application/json" \
                    https://automation.atlassian.com/pro/hooks/${{ secrets.JIRA_TRIGGER}} \
                    -d '{"issues": ["${{ github.event.inputs.key }}"], "acess_token": "${{ steps.generate-token.outputs.token }}", "specification":"${{ github.event.inputs.specifications }}"}' 
