name: Test List Jira

on:
    workflow_dispatch:
        inputs:
            test:
                description: Lista de itens
                required: true

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository content
              uses: actions/checkout@v4 

            - name: Setup python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x' 
            
            - name: testa lista
              run: |
                IFS=',' read -ra LIST <<< "${{ github.event.inputs.test }}"
                echo "KEY=${LIST[0]}" >> $GITHUB_ENV
                echo "TYPE=${LIST[0]}" >> $GITHUB_ENV
                echo "AREA=${LIST[0]}" >> $GITHUB_ENV
                echo "USER=${LIST[0]}" >> $GITHUB_ENV
            
            - name: PRINT Var
              run: |
                echo $KEY
                echo ${TYPE}

        

