name: Test List Jira

on:
    workflow_dispatch:
        inputs:
            test:
                description: Lista de itens

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository content
              uses: actions/checkout@v3 

            - name: Setup python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x' 
            
            - name: testa lista
              run: |
                echo ${{ github.event.inputs.list }}

